[const_function_cycle]
parser_errors = []
compiler_errors = ["Error: Cannot recursively reference constant. (8:5)"]

[recursive_function]
bytes = 95
cost = 10406
input = "()"
output = "120"
hash = "e287a4cdf0ee9e003ee4450c1408d162e08db92a141035bf3ff932d46ca87f93"

[const_multiple_reference]
bytes = 77
cost = 2805
input = "()"
output = "\"Hello, Bob!\""
hash = "ad1d14ebd66b8fad929ee4b816aa51410d12f987bbeabffd571d0701fe061281"

[inline_function_cycle]
parser_errors = []
compiler_errors = ["Error: Cannot recursively call inline function. (10:5)"]

[const_reference]
bytes = 31
cost = 528
input = "()"
output = "42"
hash = "e3429ee993cedb79fa5b67ebd52635a294daf9c69b1c1d1a967f884fb4c3f1d1"

[inline_const_inline_function_cycle]
parser_errors = []
compiler_errors = ["Error: Cannot recursively call inline function. (5:27)"]

[mixed_consts]
bytes = 43
cost = 2144
input = "()"
output = "126"
hash = "834c349efb47a4863d393d9266c217f5b2ab0da53d1b4cd03b1df43ac19ca85f"

[inline_const_function_cycle]
parser_errors = []
compiler_errors = ["Error: Cannot recursively reference inline constant. (8:5)"]

[inline_const_self]
parser_errors = []
compiler_errors = ["Error: Cannot recursively reference inline constant. (1:27)"]

[recursive_inline_function]
parser_errors = []
compiler_errors = ["Error: Cannot recursively call inline function. (6:5)"]

[const_inline_function_cycle]
parser_errors = []
compiler_errors = ["Error: Cannot recursively call inline function. (5:20)"]

[const_self]
parser_errors = []
compiler_errors = ["Error: Cannot recursively reference constant. (1:20)"]

[const_cycle]
parser_errors = []
compiler_errors = ["Error: Cannot recursively reference constant. (2:16)"]

[inline_const_reference]
bytes = 3
cost = 20
input = "()"
output = "42"
hash = "ce97d04b4f84066533255fcc56345626c245afd50e24c6c14c52c8e78e8b9f33"

[inline_const_inline_function_call]
bytes = 33
cost = 2965
input = "()"
output = "0x288b694028"
hash = "69389ce0c73b645b5a464c742903668325aec5dabd3899a287a99dea3feec9bd"

[const_inline_function_call]
bytes = 47
cost = 3219
input = "()"
output = "0x288b694028"
hash = "89c3c7387b014f236e551e690874afe0f922b113714d1a8e2a93948f3a4dc643"

[inline_const_function_call]
bytes = 60
cost = 3811
input = "()"
output = "0x288b694028"
hash = "c081e27512e27d099468a58b6567ba5bf0bf72ae8e90fe0db6b32c027323822d"

[const_function_call]
bytes = 74
cost = 4069
input = "()"
output = "0x288b694028"
hash = "0f74e7fd57bb9a7e05cf979ee986a8e0120801d2b18019c275a9717fce22f379"
