[package]
name = "rue-cli"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "CLI tool for the Rue compiler."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/rigidity/rue"
repository = "https://github.com/rigidity/rue"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
rue-parser = { path = "../../crates/rue-parser" }
rue-compiler = { path = "../../crates/rue-compiler" }
rue-clvm = { path = "../../crates/rue-clvm" }
clvmr = "0.6.1"
hex = "0.4.3"

[[bin]]
name = "rue"
path = "src/main.rs"
