[package]
name = "rue-parser"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Parses Rue tokens into an AST."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/rigidity/rue"
repository = "https://github.com/rigidity/rue"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
indexmap = "2.2.6"
num-derive = "0.4.2"
num-traits = "0.2.18"
rowan = "0.15.15"
rue-lexer = { path = "../rue-lexer", version = "0.1.0" }
