[package]
name = "rue-parser"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
indexmap = "2.2.6"
num-derive = "0.4.2"
num-traits = "0.2.18"
rowan = "0.15.15"
rue-lexer = { path = "../rue-lexer" }
thiserror = "1.0.58"
