[package]
name = "rue-compiler"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "The Rue compiler."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/rigidity/rue"
repository = "https://github.com/rigidity/rue"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
rue-parser = { path = "../rue-parser" }
rue-clvm = { path = "../rue-clvm" }
clvmr = "0.6.1"
id-arena = "2.2.1"
indexmap = "2.2.6"
rowan = "0.15.15"
num-traits = "0.2.18"
num-bigint = "0.4.4"
log = "0.4.21"
hex = "0.4.3"
indoc = "2.0.5"
