[package]
name = "rue-lsp"
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
description = "Provides a language server for Rue."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/rigidity/rue"
repository = "https://github.com/rigidity/rue"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[dependencies]
rue-parser = { path = "../rue-parser", version = "0.1.0" }
rue-compiler = { path = "../rue-compiler", version = "0.1.0" }
tokio = { version = "1.37.0", features = ["full"] }
tower-lsp = "0.20.0"
clvmr = "0.6.1"
