[package]
name = "rue-lsp"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
rue-parser = { path = "../rue-parser" }
rue-compiler = { path = "../rue-compiler" }
tokio = { version = "1.37.0", features = ["full"] }
tower-lsp = "0.20.0"
